'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bica.CursoDotNet2019.Datos

    Partial Public Class Cliente
        Public Property Id As Long
        Public Property IdPersona As Long
        Public Property Categoria As String
        Public Property Codigo As String
    
        Public Overridable Property Persona As Persona
    
    End Class

End Namespace
