'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Bica.CursoDotNet2019.Datos

    Partial Public Class B_CursoDotNetEntities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=B_CursoDotNetEntities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Persona() As DbSet(Of Persona)
        Public Overridable Property Cliente() As DbSet(Of Cliente)
        Public Overridable Property Vendedor() As DbSet(Of Vendedor)
    
    End Class

End Namespace
