'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Bica.CursoDotNet2019.Datos

    Partial Public Class Persona
        Public Property Id As Long
        Public Property Nombres As String
        Public Property Apellidos As String
        Public Property Telefono As String
        Public Property Documento As Integer
        Public Property TipoDocumento As Integer
        Public Property TipoPersona As Integer
    
        Public Overridable Property Cliente As ICollection(Of Cliente) = New HashSet(Of Cliente)
        Public Overridable Property Vendedor As ICollection(Of Vendedor) = New HashSet(Of Vendedor)
    
    End Class

End Namespace
